"""
Main FastAPI application for User Management Service.
Entry point for the service.
"""

import logging
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.openapi.utils import get_openapi
from contextlib import asynccontextmanager

# Import database and configuration
from .database.connection import init_db, close_db
from .config.settings import settings

# Import JWT config setup (from Auth Service's shared security module)
import sys
from pathlib import Path

# Add auth_service to path to import shared security modules
auth_service_path = str(Path(__file__).parent.parent.parent / "auth_service" / "app")
if auth_service_path not in sys.path:
    sys.path.insert(0, auth_service_path)

try:
    from security.auth_dependencies import set_jwt_config
except ImportError:
    # Fallback: try direct path
    auth_service_parent = str(Path(__file__).parent.parent.parent / "auth_service")
    if auth_service_parent not in sys.path:
        sys.path.insert(0, auth_service_parent)
    from app.security.auth_dependencies import set_jwt_config

from .api.add_user_routes import router as add_user_router
from .api.edit_user_routes import router as edit_user_router
from .api.view_user_routes import router as view_user_router
from .api.inactivate_user_routes import router as inactivate_user_router
from .api.activate_user_routes import router as activate_user_router
from .api.internal_user_routes import router as internal_user_router

# Configure logging
logging.basicConfig(
    level=getattr(logging, settings.LOG_LEVEL),
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    FastAPI lifespan context manager.
    Handles startup and shutdown events.
    """
    # Startup
    logger.info("🚀 Starting User Management Service...")
    
    # Initialize JWT config for authorization
    try:
        set_jwt_config(
            secret_key=settings.JWT_SECRET_KEY,
            algorithm=settings.JWT_ALGORITHM,
        )
        logger.info("✅ JWT config initialized")
    except Exception as e:
        logger.error(f"Failed to initialize JWT config: {str(e)}")
        raise
    
    await init_db()
    logger.info("✅ Service started successfully")
    yield

    # Shutdown
    logger.info("⏹️ Shutting down User Management Service...")
    await close_db()
    logger.info("✅ Service shut down successfully")


# Create FastAPI app with docs at /api/v1/docs
app = FastAPI(
    title=settings.TITLE,
    description=settings.DESCRIPTION,
    version=settings.SERVICE_VERSION,
    lifespan=lifespan,
    docs_url="/api/v1/docs",
    redoc_url="/api/v1/redoc",
    openapi_url="/api/v1/openapi.json",
)

# Add OpenAPI security scheme for Bearer token
def custom_openapi():
    """Custom OpenAPI schema with Bearer token security."""
    if app.openapi_schema:
        return app.openapi_schema
    
    # Get the default OpenAPI schema generated by FastAPI
    openapi_schema = get_openapi(
        title=settings.TITLE,
        version=settings.SERVICE_VERSION,
        description=settings.DESCRIPTION,
        routes=app.routes,
    )
    
    # Add Bearer token security scheme
    openapi_schema["components"]["securitySchemes"] = {
        "Bearer": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT",
            "description": "JWT Bearer token. Get from Auth Service /login endpoint",
        }
    }
    
    # Apply security to all endpoints
    openapi_schema["security"] = [{"Bearer": []}]
    
    app.openapi_schema = openapi_schema
    return app.openapi_schema

app.openapi = custom_openapi

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)(:\d+)?|https?://.*\.onrender\.com",
    allow_credentials=settings.CORS_CREDENTIALS,
    allow_methods=settings.CORS_METHODS,
    allow_headers=settings.CORS_HEADERS,
)


# Include all route routers
app.include_router(add_user_router)
app.include_router(edit_user_router)
app.include_router(view_user_router)
app.include_router(inactivate_user_router)
app.include_router(activate_user_router)
app.include_router(internal_user_router)


@app.get("/api/v1/health", tags=["Health"])
async def health_check():
    """
    Health check endpoint.
    Returns service status.
    """
    return {
        "status": "healthy",
        "service": settings.SERVICE_NAME,
        "version": settings.SERVICE_VERSION,
    }


@app.get("/", tags=["Root"])
async def root():
    """Root endpoint with service information."""
    return {
        "service": settings.SERVICE_NAME,
        "version": settings.SERVICE_VERSION,
        "docs": "/api/v1/docs",
        "health": "/api/v1/health",
    }


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        "app.main:app",
        host=settings.HOST,
        port=settings.PORT,
        reload=settings.DEBUG,
    )
